/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AttackProgressionRouteImport } from './routes/attack-progression'
import { Route as EventTimelineRouteImport } from './routes/event-timeline'
import { Route as ExplainabilityRouteImport } from './routes/explainability'
import { Route as NetworkStateRouteImport } from './routes/network-state'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SystemHealthRouteImport } from './routes/system-health'
import { Route as ThreatForecastRouteImport } from './routes/threat-forecast'
import { Route as InvestigationIdRouteImport } from './routes/investigation.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AttackProgressionRoute = AttackProgressionRouteImport.update({
  id: '/attack-progression',
  path: '/attack-progression',
  getParentRoute: () => rootRouteImport,
} as any)
const EventTimelineRoute = EventTimelineRouteImport.update({
  id: '/event-timeline',
  path: '/event-timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplainabilityRoute = ExplainabilityRouteImport.update({
  id: '/explainability',
  path: '/explainability',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworkStateRoute = NetworkStateRouteImport.update({
  id: '/network-state',
  path: '/network-state',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemHealthRoute = SystemHealthRouteImport.update({
  id: '/system-health',
  path: '/system-health',
  getParentRoute: () => rootRouteImport,
} as any)
const ThreatForecastRoute = ThreatForecastRouteImport.update({
  id: '/threat-forecast',
  path: '/threat-forecast',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestigationIdRoute = InvestigationIdRouteImport.update({
  id: '/investigation/$id',
  path: '/investigation/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/attack-progression': typeof AttackProgressionRoute
  '/event-timeline': typeof EventTimelineRoute
  '/explainability': typeof ExplainabilityRoute
  '/network-state': typeof NetworkStateRoute
  '/settings': typeof SettingsRoute
  '/system-health': typeof SystemHealthRoute
  '/threat-forecast': typeof ThreatForecastRoute
  '/investigation/$id': typeof InvestigationIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/attack-progression': typeof AttackProgressionRoute
  '/event-timeline': typeof EventTimelineRoute
  '/explainability': typeof ExplainabilityRoute
  '/network-state': typeof NetworkStateRoute
  '/settings': typeof SettingsRoute
  '/system-health': typeof SystemHealthRoute
  '/threat-forecast': typeof ThreatForecastRoute
  '/investigation/$id': typeof InvestigationIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/attack-progression': typeof AttackProgressionRoute
  '/event-timeline': typeof EventTimelineRoute
  '/explainability': typeof ExplainabilityRoute
  '/network-state': typeof NetworkStateRoute
  '/settings': typeof SettingsRoute
  '/system-health': typeof SystemHealthRoute
  '/threat-forecast': typeof ThreatForecastRoute
  '/investigation/$id': typeof InvestigationIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/attack-progression'
    | '/event-timeline'
    | '/explainability'
    | '/network-state'
    | '/settings'
    | '/system-health'
    | '/threat-forecast'
    | '/investigation/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/attack-progression'
    | '/event-timeline'
    | '/explainability'
    | '/network-state'
    | '/settings'
    | '/system-health'
    | '/threat-forecast'
    | '/investigation/$id'
  id:
    | '__root__'
    | '/'
    | '/attack-progression'
    | '/event-timeline'
    | '/explainability'
    | '/network-state'
    | '/settings'
    | '/system-health'
    | '/threat-forecast'
    | '/investigation/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AttackProgressionRoute: typeof AttackProgressionRoute
  EventTimelineRoute: typeof EventTimelineRoute
  ExplainabilityRoute: typeof ExplainabilityRoute
  NetworkStateRoute: typeof NetworkStateRoute
  SettingsRoute: typeof SettingsRoute
  SystemHealthRoute: typeof SystemHealthRoute
  ThreatForecastRoute: typeof ThreatForecastRoute
  InvestigationIdRoute: typeof InvestigationIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attack-progression': {
      id: '/attack-progression'
      path: '/attack-progression'
      fullPath: '/attack-progression'
      preLoaderRoute: typeof AttackProgressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event-timeline': {
      id: '/event-timeline'
      path: '/event-timeline'
      fullPath: '/event-timeline'
      preLoaderRoute: typeof EventTimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explainability': {
      id: '/explainability'
      path: '/explainability'
      fullPath: '/explainability'
      preLoaderRoute: typeof ExplainabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/network-state': {
      id: '/network-state'
      path: '/network-state'
      fullPath: '/network-state'
      preLoaderRoute: typeof NetworkStateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system-health': {
      id: '/system-health'
      path: '/system-health'
      fullPath: '/system-health'
      preLoaderRoute: typeof SystemHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/threat-forecast': {
      id: '/threat-forecast'
      path: '/threat-forecast'
      fullPath: '/threat-forecast'
      preLoaderRoute: typeof ThreatForecastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investigation/$id': {
      id: '/investigation/$id'
      path: '/investigation/$id'
      fullPath: '/investigation/$id'
      preLoaderRoute: typeof InvestigationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AttackProgressionRoute: AttackProgressionRoute,
  EventTimelineRoute: EventTimelineRoute,
  ExplainabilityRoute: ExplainabilityRoute,
  NetworkStateRoute: NetworkStateRoute,
  SettingsRoute: SettingsRoute,
  SystemHealthRoute: SystemHealthRoute,
  ThreatForecastRoute: ThreatForecastRoute,
  InvestigationIdRoute: InvestigationIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
